services:
  db:
    container_name: pg__twitter__container
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: dwa
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"
    volumes:
      - pg_tc_data:/var/lib/postgresql/data

volumes:
  pg_tc_data:
